package com.example.marcos.bolaocopadomundo.util;

import com.example.marcos.bolaocopadomundo.R;
import com.example.marcos.bolaocopadomundo.model.Jogo;

import java.util.ArrayList;
import java.util.List;

public class Util {
    public Util() {
    }

    public List<Jogo>TabelaPrimeiraFase(){
        List<Jogo> jogos = new ArrayList<>();

        jogos.add(new Jogo("Rússia",
                0,
                R.drawable.russia_round_icon_64,
                "Arábia",
                0,
                R.drawable.saudi_arabia_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Qui 14/06/2018",
                "12:00"));
        jogos.add(new Jogo("Egito",
                0,
                R.drawable.egypt_round_icon_64,
                "Uruguai",
                0,
                R.drawable.uruguay_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sex 15/06/2018",
                "09:00"));
        jogos.add(new Jogo("Marrocos",
                0,
                R.drawable.morocco_round_icon_64,
                "Irã",
                0,
                R.drawable.iran_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sex 15/06/2018",
                "12:00"));
        jogos.add(new Jogo("Portugal",
                0,
                R.drawable.portugal_round_icon_64,
                "Espanha",
                0,
                R.drawable.spain_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sex 15/06/2018",
                "15:00"));
        jogos.add(new Jogo("França",
                0,
                R.drawable.france_round_icon_64,
                "Austrália",
                0,
                R.drawable.australia_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sab 16/06/2018",
                "07:00"));
        jogos.add(new Jogo("Peru",
                0,
                R.drawable.peru_round_icon_64,
                "Dinamarca",
                0,
                R.drawable.denmark_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sab 16/06/2018",
                "13:00"));
        jogos.add(new Jogo("Argentina",
                0,
                R.drawable.argentina_round_icon_64,
                "Islândia",
                0,
                R.drawable.iceland_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sab 16/06/2018",
                "10:00"));
        jogos.add(new Jogo("Croácia",
                0,
                R.drawable.croatia_round_icon_64,
                "Nigéria",
                0,
                R.drawable.nigeria_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Sab 16/06/2018",
                "16:00"));
        jogos.add(new Jogo("Costa Rica",
                0,
                R.drawable.costa_rica_round_icon_64,
                "Sérvia",
                0,
                R.drawable.serbia_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Dom 17/06/2018",
                "09:00"));
        jogos.add(new Jogo("Brasil",
                0,
                R.drawable.brazil_round_icon_64,
                "Suíça",
                0,
                R.drawable.switzerland_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Dom 17/06/2018",
                "15:00"));
        jogos.add(new Jogo("Alemanha",
                0,
                R.drawable.germany_round_icon_64,
                "México",
                0,
                R.drawable.mexico_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Dom 17/06/2018",
                "12:00"));
        jogos.add(new Jogo("Suécia",
                0,
                R.drawable.sweden_round_icon_64,
                "Coréia",
                0,
                R.drawable.korea_south_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Seg 18/06/2018 ",
                "09:00"));
        jogos.add(new Jogo("Bélgica",
                0,
                R.drawable.belgium_round_icon_64,
                "Panamá",
                0,
                R.drawable.panama_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Seg 18/06/2018 ",
                "12:00"));
        jogos.add(new Jogo("Tunísia",
                0,
                R.drawable.tunisia_round_icon_64,
                "Inglaterra",
                0,
                R.drawable.england_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Seg 18/06/2018 ",
                "15:00"));
        jogos.add(new Jogo("Colômbia",
                0,
                R.drawable.colombia_round_icon_64,
                "Japão",
                0,
                R.drawable.japan_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Ter 19/06/2018 ",
                "09:00"));
        jogos.add(new Jogo("Polônia",
                0,
                R.drawable.poland_round_icon_64,
                "Senegal",
                0,
                R.drawable.senegal_round_icon_64,
                "rodada 1",
                "fase 1",
                "",
                "Ter 19/06/2018 ",
                "12:00"));
        jogos.add(new Jogo("Rússia",
                0,
                R.drawable.russia_round_icon_64,
                "Egito",
                0,
                R.drawable.egypt_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Ter 19/06/2018",
                "15:00"));
        jogos.add(new Jogo("Uruguai",
                0,
                R.drawable.uruguay_round_icon_64,
                "Arábia",
                0,
                R.drawable.saudi_arabia_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qua 20/06/2018",
                "12:00"));
        jogos.add(new Jogo("Portugal",
                0,
                R.drawable.portugal_round_icon_64,
                "Marrocos",
                0,
                R.drawable.morocco_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qua 20/06/2018",
                "09:00"));
        jogos.add(new Jogo("Irã",
                0,
                R.drawable.iran_round_icon_64,
                "Espanha",
                0,
                R.drawable.spain_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qua 20/06/2018",
                "15:00"));
        jogos.add(new Jogo("Dinamarca",
                0,
                R.drawable.denmark_round_icon_64,
                "Austrália",
                0,
                R.drawable.australia_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qui 21/06/2018",
                "09:00"));
        jogos.add(new Jogo("França",
                0,
                R.drawable.france_round_icon_64,
                "Peru",
                0,
                R.drawable.peru_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qui 21/06/2018",
                "12:00"));
        jogos.add(new Jogo("Argentina",
                0,
                R.drawable.argentina_round_icon_64,
                "Croácia",
                0,
                R.drawable.croatia_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qui 21/06/2018",
                "15:00"));
        jogos.add(new Jogo("Nigéria",
                0,
                R.drawable.nigeria_round_icon_64,
                "Islândia",
                0,
                R.drawable.iceland_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Sex 22/06/2018",
                "12:00"));
        jogos.add(new Jogo("Brasil",
                0,
                R.drawable.brazil_round_icon_64,
                "Costa Rica",
                0,
                R.drawable.costa_rica_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Sex 22/06/2018",
                "09:00"));
        jogos.add(new Jogo("Sérvia",
                0,
                R.drawable.serbia_round_icon_64,
                "Suíça",
                0,
                R.drawable.switzerland_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Sex 22/06/2018",
                "15:00"));
        jogos.add(new Jogo("Coréia",
                0,
                R.drawable.korea_south_round_icon_64,
                "México",
                0,
                R.drawable.mexico_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Sab 23/06/2018",
                "12:00"));
        jogos.add(new Jogo("Alemanha",
                0,
                R.drawable.germany_round_icon_64,
                "Suécia",
                0,
                R.drawable.sweden_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Sab 23/06/2018",
                "15:00"));
        jogos.add(new Jogo("França",
                0,
                R.drawable.france_round_icon_64,
                "Peru",
                0,
                R.drawable.peru_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Qui 21/06/2018",
                "12:00"));
        jogos.add(new Jogo("Bélgica",
                0,
                R.drawable.belgium_round_icon_64,
                "Tunísia",
                0,
                R.drawable.tunisia_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Sab 23/06/2018 ",
                "09:00"));
        jogos.add(new Jogo("Inglaterra",
                0,
                R.drawable.england_round_icon_64,
                "Panamá",
                0,
                R.drawable.panama_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Dom 24/06/2018",
                "09:00"));
        jogos.add(new Jogo("Japão",
                0,
                R.drawable.japan_round_icon_64,
                "Senegal",
                0,
                R.drawable.senegal_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Dom 24/06/2018",
                "12:00"));
        jogos.add(new Jogo("Polônia",
                0,
                R.drawable.poland_round_icon_64,
                "Colômbia",
                0,
                R.drawable.colombia_round_icon_64,
                "rodada 2",
                "fase 1",
                "",
                "Dom 24/06/2018",
                "15:00"));
        jogos.add(new Jogo("Uruguai",
                0,
                R.drawable.uruguay_round_icon_64,
                "Rússia",
                0,
                R.drawable.russia_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Seg 25/06/2018",
                "11:00"));
        jogos.add(new Jogo("Arábia",
                0,
                R.drawable.saudi_arabia_round_icon_64,
                "Egito",
                0,
                R.drawable.egypt_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Seg 25/06/2018",
                "11:00"));
        jogos.add(new Jogo("Irã",
                0,
                R.drawable.iran_round_icon_64,
                "Portugal",
                0,
                R.drawable.portugal_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Seg 25/06/2018",
                "15:00"));
        jogos.add(new Jogo("Espanha",
                0,
                R.drawable.spain_round_icon_64,
                "Marrocos",
                0,
                R.drawable.morocco_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Seg 25/06/2018",
                "15:00"));
        jogos.add(new Jogo("Dinamarca",
                0,
                R.drawable.denmark_round_icon_64,
                "França",
                0,
                R.drawable.france_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Ter 26/06/2018 ",
                "11:00"));
        jogos.add(new Jogo("Austrália",
                0,
                R.drawable.australia_round_icon_64,
                "Peru",
                0,
                R.drawable.peru_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Ter 26/06/2018 ",
                "11:00"));
        jogos.add(new Jogo("Nigéria",
                0,
                R.drawable.nigeria_round_icon_64,
                "Argentina",
                0,
                R.drawable.argentina_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Ter 26/06/2018",
                "15:00"));
        jogos.add(new Jogo("Islândia",
                0,
                R.drawable.iceland_round_icon_64,
                "Croácia",
                0,
                R.drawable.croatia_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Ter 26/06/2018",
                "15:00"));
        jogos.add(new Jogo("Sérvia",
                0,
                R.drawable.serbia_round_icon_64,
                "Brasil",
                0,
                R.drawable.brazil_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qua 27/06/2018 ",
                "15:00"));
        jogos.add(new Jogo("Suíça",
                0,
                R.drawable.switzerland_round_icon_64,
                "Costa Rica",
                0,
                R.drawable.costa_rica_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qua 27/06/2018 ",
                "15:00"));
        jogos.add(new Jogo("Coréia",
                0,
                R.drawable.korea_south_round_icon_64,
                "Alemanha",
                0,
                R.drawable.germany_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qua 27/06/2018 ",
                "11:00"));
        jogos.add(new Jogo("México",
                0,
                R.drawable.mexico_round_icon_64,
                "Suécia",
                0,
                R.drawable.sweden_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qui 28/06/2018 ",
                "15:00"));
        jogos.add(new Jogo("Inglaterra",
                0,
                R.drawable.england_round_icon_64,
                "Bélgica",
                0,
                R.drawable.belgium_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qui 28/06/2018 ",
                "15:00"));
        jogos.add(new Jogo("Panamá",
                0,
                R.drawable.panama_round_icon_64,
                "Tunísia",
                0,
                R.drawable.tunisia_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Seg 25/06/2018",
                "11:00"));
        jogos.add(new Jogo("Japão",
                0,
                R.drawable.japan_round_icon_64,
                "Polônia",
                0,
                R.drawable.poland_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qui 28/06/2018 ",
                "11:00"));
        jogos.add(new Jogo("Senegal",
                0,
                R.drawable.senegal_round_icon_64,
                "Colômbia",
                0,
                R.drawable.colombia_round_icon_64,
                "rodada 3",
                "fase 1",
                "",
                "Qui 28/06/2018 ",
                "11:00"));

        return jogos;
    }
}
